# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    groups:
      # Group all GitHub Actions updates into a single pull request
      github-actions:
        patterns:
          - "*"
